apiVersion: v1
kind: Service
metadata:
  name: linkedin-responder
  namespace: linkedin-responder
spec:
  selector:
    app: linkedin-responder
  ports:
    - port: 80
      targetPort: 8000
  type: ClusterIP
